#include <stdio.h>
#include <stdlib.h>
#include "lexer.c"
#include "utils.c"
#include "parser.c"
// #include "ad.c"
// #include "at.h"
#include "at.c"
#include "ad.c"
#include "vm.c"

int main() {
    // char* inbuf = loadFile("tests/testat.c"); // for type analyzer testing
    char* inbuf = loadFile("tests/testgc.c"); // for code gen testing
    // puts(inbuf);

    puts(inbuf);
    Token* tokens = tokenize(inbuf);
    // showTokens(tokens);
    pushDomain();
    vmInitD();
    parse(tokens);
    showDomain(symTable, "global");
    Symbol* symMain = findSymbolInDomain(symTable, "main");
    if (!symMain)err("missing main function");
    Instr* entryCode = NULL;
    Instr* testCode = genTestProgram();
    run(testCode);
    
    // addInstr(&entryCode, OP_CALL)->arg.instr = symMain->fn.instr;
    // addInstr(&entryCode, OP_HALT);
    // run(entryCode);

    printf("\n-----------------------------------------------------------------\n");

    Instr* testCode2 = genTestProgram2();
    // vmInit(); // Initialize the virtual machine
    run(testCode2); // Execute the generated bytecode

    dropDomain();
    // showTokens(tokenize(inbuf));
    // parse(tokenize(inbuf));
    return 0;
}